### PR TITLE
Add new default rules

### PR DESCRIPTION
**Pull request by jesmg**
Add more default rules to Gitleaks, based on [Trufflehog](https://github.com/dxa4481/truffleHog)  ruleset but with minor fixes.

### CODE REVIEW

**Comment by jesmg** [comment]
I made the following repo for testing the rules: https://github.com/jesmg/secretsRepo

**Comment by zricethezav** [comment]
Hey @jesmg I actually was just working on this yesterday. I have a branch here: https://github.com/zricethezav/gitleaks/commit/94482022264981258ac635de42659a25f0028c5e If you want to update your PR with the rules I supplied (couple of changes that I prefer like `(?i)` for case insensitivity and limits on the regexes) then I'd be happy to merge this PR.

**Comment by jesmg** [comment]
Sure, I will do it! ;)

Thanks

**Comment by jesmg** [comment]
> Hey @jesmg I actually was just working on this yesterday. I have a branch here: [9448202](https://github.com/zricethezav/gitleaks/commit/94482022264981258ac635de42659a25f0028c5e) If you want to update your PR with the rules I supplied (couple of changes that I prefer like `(?i)` for case insensitivity and limits on the regexes) then I'd be happy to merge this PR.

Updated!

**Pull request merged**
