### PR TITLE
Update pre-commit step to run gitleaks checks

### PR DESCRIPTION
**Pull request by veleek**
### Description:
The current `entry` value for the pre-commit config causes it to just run gitleaks with no command.  This runs the same command that as defined in the `scripts/pre-commit.py` except that it doesn't check whether `git config --bool hooks.gitleaks` is true, but it's probably safe to assume that if it's configured as a pre-commit check then it should be okay to run it.

### Checklist:

* [X] Does your PR pass tests? Not a go code change.
* [X] Have you written new tests for your changes? N/A
* [X] Have you lint your code locally prior to submission? Not a go code change.

### CODE REVIEW

**Comment by veleek** [comment]
Should this command run with --redacted?

**Comment by zricethezav** [comment]
@veleek awesome, thanks for the PR.

> Should this command run with --redacted?

That makes sense to me, good to hide secrets from the terminal's scroll history

**Comment by veleek** [comment]
@zricethezav - Hold off on this merging this change.  I'm running into a problem where this is hanging, and I think it's the same error as #724.  Adding more detail to that issue.

**Comment by zricethezav** [comment]
@veleek ping me when this PR is ready and I'll get it merged in

**Comment by veleek** [comment]
So this works if you're running pre-commit locally (e.g. as an actually git pre-commit hook) which runs it's checks against any staged files.  This matches the `--staged` flag that's passed to the tool.  Unfortunately, when running pre-commit as a Github action, the `--all-files` flag is passed to pre-commit so that the script runs against everything because it's running against a merged branch so there aren't any files staged.  

https://github.com/pre-commit/action/blob/master/action.yml

So works, locally as a GH Action, not really sure what the expected way to fix this would be.  I _think_ the correct thing to do would be to change gitleaks to read the filenames to process from the ones passed by pre-commit.  So pre-commit wouldn't need to use the `--staged` flag at all.  Bigger change for gitleaks though, so I say accept this PR as is and add an issue to make it work when using `--all-files` on pre-commit later.

**Comment by zricethezav** [comment]
@veleek I'm glad to hear it works locally as that is the most important time to catch secrets before they are committed. 

> Unfortunately, when running pre-commit as a Github action, the --all-files flag is passed to pre-commit so that the script runs against everything because it's running against a merged branch so there aren't any files staged.

Gitleaks should be running `detect` during github actions as changes have already been committed. Or am I misunderstanding something?

**Comment by chriselion** [comment]
> Gitleaks should be running `detect` during github actions as changes have already been committed. Or am I misunderstanding something?

I think that makes sense, but currently it's not possible to do that via the pre-commit hook.

Maybe a solution would be to add another hook that runs `detect`? I think that would look something like

```
- id: gitleaks-detect
  name: TODO
  description: TODO
  entry: gitleaks detect --no-git --redact
  args: ["--verbose"]
  language: golang
```

That will result in multiple files being passed after the entry and args, so the final command line would look like `gitleaks detect --no-git --redact --verbose foo.txt bar.go baz.py`. Am I correct in my reading of the docs that this will run on just the contents of those 3 files (not their git history)? 

Side note: it's up to you, but I feel like `--verbose` should be optional; by putting it in `args`, the user can still override it.

**Pull request merged**
