### PR TITLE
Add feature to scan a GitLab commit through a commit link

### PR DESCRIPTION
**Pull request by macedogm**
### Description:
This PR adds a feature to allow scanning of a commit diff in GitLab through the commit link.

The commit link can be in one of two formats:
1. https://gitlab.com/gitlab-org/gitlab/-/commit/39264445dde9de4772e57bfaf368fc69b8942d53
2. https://gitlab.com/gitlab-org/gitlab/commit/39264445dde9de4772e57bfaf368fc69b8942d53 

### Checklist:

* [ ] Does your PR pass tests?
* [ ] Have you written new tests for your changes?
* [X] Have you lint your code locally prior to submission?

### CODE REVIEW

**Comment by macedogm** [comment]
Hi @zricethezav .
Is there anything that I can do to help with the review of this MR, please?
Best regards.

**Comment by zricethezav** [comment]
I am no longer supporting gitlab/github integrations

**Comment by macedogm** [comment]
Hey @zricethezav! 👋🏻 
Sorry, I was not aware of that. If you are dropping support for both GitLab and GitHub integrations, may I ask then what are the plans for the tool?
Are you looking for someone to help maintain it?
Best regards.

**Comment by zricethezav** [comment]
@macedogm I basically got sick of the flood of requests for helping with issues w/r/t Gitlab/Github integrations. I want gitleaks to be the fastest, most configurable secret scanner, not scanner with the most built-in extensions. Gitlab/Github integrations felt like half-baked feature creep. If someone wants to integrate with gitlab/github I recommend creating a script that wraps gitleaks or create a new project that recycles some of gitleaks' code.

I'm not looking for any help maintaining gitleaks now, but that might change. There are some items that need doing like increasing test coverage in the config package, making better documentation, and creating some more option guards.

**Pull request closed without merging**
