### PR TITLE
No longer generate empty reports

### LINKED ISSUE #524: Gitleaks generates empty report (0KB)
**Describe the bug**
On Windows, gitleaks writes an empty (0KB) report file to whichever directory I specify, regardless of number of leaks found.  This occurs for both both JSON and CSV report format.

After running the following command: 
`> gitleaks.exe --path=<PATH_TO_REPO> --branch=master --report=report.csv --format=CSV --config-path=scanner.config`

Log output is the following: 
```
time="2021-02-10T09:28:43-11:00" level=info msg="opening <PATH_TO_REPO>\n"
time="2021-02-10T09:59:53-11:00" level=info msg="scan time: 37 minutes 19 seconds 343 milliseconds 912 microseconds"
time="2021-02-10T09:59:53-11:00" level=info msg="commits scanned: 5971"
time="2021-02-10T09:59:53-11:00" level=warning msg="leaks found: 203"
```

The report.csv or report.json is always 0KB.

**To Reproduce**
Run gitleaks on local git repository with either `--report=report.csv --format=CSV` or `--report=report.json --format=JSON` flags set.

**Expected behavior**
I expect the report.csv or report.json to contain data, but it always generates an empty file (0KB)

**Screenshots**
N/A

**Basic Info (please complete the following information):**
 - OS: Microsoft Windows 10 Enterprise Edition
 - Gitleaks Version: v7.2.2

**Additional context**
Assume CMD calling gitleaks.exe from the same directory, and git repository is one level down.

cc @zricethezav

### PR DESCRIPTION
**Pull request by eddie-austin**
### Description:
- Fixes #524 Gitleaks generates empty report
- Return nil when no leaks are found so an empty report is not created

### Checklist:

* [x] Does your PR pass tests?
* [ ] Have you written new tests for your changes?
* [x] Have you lint your code locally prior to submission?

### CODE REVIEW

**Review by w0rmr1d3r — COMMENTED** [review]
Nice Pr @eddie-austin !
Can you update the documentation as well?
Thank you!

**Comment by eddie-austin** [comment]
@w0rmr1d3r I've updated the documentation

**Comment by eddie-austin** [comment]
@w0rmr1d3r No worries! I've updated the description in `options.go` 😄

**Review by w0rmr1d3r — APPROVED** [review]
It's an approve from my side, let's see what @zricethezav thinks!

**Comment by w0rmr1d3r** [comment]
@zricethezav can we give this a go and close the linked issue https://github.com/zricethezav/gitleaks/issues/524 and this discussion https://github.com/zricethezav/gitleaks/discussions/568 ?

**Comment by zricethezav** [comment]
@eddie-austin thanks for the PR! and thanks for bringing this to my attention @w0rmr1d3r

**Pull request merged**
