### PR TITLE
Scan local repos

### PR DESCRIPTION
**Pull request by timdev21**
Added functionality mentioned in #15 

* Added possibility to scan local repos
* Added --persist flag to keep cloned repositories after scan

### CODE REVIEW

**Comment by zricethezav** [comment]
This is great, thanks! I'll look at it more closely this evening. 👍

**Comment by ryan-copperleaf** [comment]
The README change suggests `gitleaks -d repo` will delete an existing repo? That seems dangerous. Maybe it should imply `-p`.

**Comment by zricethezav** [comment]
still need ability to do this. Will be working on in next version bump

**Comment by jordan2936** [comment]
Man I’m trying my hardest to figure this out

**Pull request closed without merging**
