### PR TITLE
Include `offenderEntropy` in the JSON output

### PR DESCRIPTION
**Pull request by bplaxco**
### Description:
Include `offenderEntropy` in the JSON output to:
1. Make it easier to tune the rules
2. Provide more information to downstream systems that consume the json to reason about potential false positives.

### Checklist:

* [x] Does your PR pass tests? (`make test` runs clean locally)
* [ ] Have you written new tests for your changes? (See "Notes" below)
* [X] Have you lint your code locally prior to submission? (ran `golint` and `go fmt` as part of the tests)

#### Testing
I was having a little trouble getting the tests to fail messing around with the test data to confirm it failed before adding in my tests. Just wanted to confirm, what is your usual testing flow? I'd love to add more tests to make sure the cases are covered :) 

My team maintains a leak-patterns repo internally and it did pass when running it through those tests. And I manually ran it through:
* Entropy within range (returns the value in the JSON)
* Entropy to high for range (no results)
* Entropy to low for range (no results)
* Entropy not checked but regex match (entropy comes back as -1)

(I have not done any heavy performance testing though)

#### Matching style & Semantic Go
I tried to match the style of the project because go's not my day-to-day language. If I'm off on anything or you'd like me to tweak anything about it, just let me know.

#### Example output runing it against my [fake-leaks](https://github.com/bplaxco/fake-leaks) repo:

```
{
        "line": "SECRET_KEY = \"zbdcj20y@s%kvfhjc4#\u0026ira)g(isr-ee0wqr18wr)(s0k^3g%k\"",
        "lineNumber": 1,
        "offender": "SECRET_KEY = \"zbdcj20y@s%kvfhjc4#\u0026ira)g(isr-ee0wqr18wr)(s0k^3g%k\"", 
        "offenderEntropy": 4.838562939644918,
        "commit": "acecd1ba2c37cba21aef8f96d5acc2dd9cb0bf85",
        "repo": "fake-leaks",
        "repoURL": "https://github.com/bplaxco/fake-leaks",
        "leakURL": "https://github.com/bplaxco/fake-leaks/blob/acecd1ba2c37cba21aef8f96d5acc2dd9cb0bf85/settings/django/settings.py#L1",
        "rule": "Django Secret Key",
        "commitMessage": "Add fake Django secret key\n\nThis is to test if my secrets scanner can pick up Django secret keys.\n\n~ B'ezrat Hashem ~\n",
        "author": "Braxton Plaxco",
        "email": "bplaxco@lupnix.org",
        "file": "settings/django/settings.py",
        "date": "2021-03-17T08:13:59-04:00",
        "tags": "key, django"
}
```

### CODE REVIEW

**Comment by zricethezav** [comment]
@bplaxco thanks so much for this contribution. I definitely want to add this feature! 

> I was having a little trouble getting the tests to fail messing around with the test data to confirm it failed before adding in my tests. Just wanted to confirm, what is your usual testing flow? I'd love to add more tests to make sure the cases are covered :)

So typically my testing flow is whenever I add or change code that affects the report I'll add or update tests in `scan_test.go`. The test table is getting a little out of control... I plan on reorganizing the tests eventually.

Anyways, the reason why your tests were passing when they should be failing since you are adding an additional entry in the leak struct, is because of this [code here](https://github.com/zricethezav/gitleaks/blob/master/scan/scan_test.go#L773-L811). You'll need to add `offenderEntropy` to that function. 

If you end up not being able to add a test, let me know. I can work on adding some tests but it might take a little while longer

**Comment by bplaxco** [comment]
Ah, cool cool. I'll to update the tests to handle the changes. Thank you for pointing out where to do that :ok_hand:

**Comment by bplaxco** [comment]
Summary of the changes:

* Rebased on the latest changes
* Updated `same`, got breaking tests, and then made changes to the test files and got them passing
* Rounded the offenderEntropy to make the tests more stable (I was running into a case where it was changing each run)
* Resolved some small things that the linter was complaining about that I didn't notice before.
* Tweaked the error output of the tests to help me debug problems a bit faster

I *think* that should be good to go, I tried to make sure all of the entropy checks were reporting a non negative number. If there is anything you'd like me to tweak, just let me know :)

**Comment by zricethezav** [comment]
@bplaxco This looks great! The only blocking thing is you still have some `.got` files in the tests, could you remove those?

**Comment by bplaxco** [comment]
@zricethezav ah, my bad. Those should be removed now :+1:  

Any reason to not throw `*.got` in the `.gitignore`?

**Comment by zricethezav** [comment]
> @zricethezav ah, my bad. Those should be removed now 👍
> 
> Any reason to not throw `*.got` in the `.gitignore`?

@bplaxco Nope! Care to add that in this PR?

**Comment by bplaxco** [comment]
@zricethezav added :+1:

**Review by zricethezav — APPROVED** [review]

**Comment by zricethezav** [comment]
@bplaxco great addition! This will go into the next release 😄

**Pull request merged**
