### PR TITLE
feat/report-writer: supporting AWS S3 and syslog, and multiple report outputs

### PR DESCRIPTION
**Pull request by mtulio**
Supporting new report outputs to:
- AWS S3 bucket
- syslog remote server
- multiple outputs

## AWS S3 bucket

The output object will be saved in **JSON** format directly to the object path in argument --report.  See more on README

## Syslog

The output object will be saved in **JSON** sending the payload, by leak result, to Sylog server. See more on README

## Multiple output

Now, to keep compatibility and improve the report options, multiple outputs could be informed spited by comma. See more on README

### CODE REVIEW

**Comment by avishnyakov** [comment]
Nice work but there is a question if this is something GitLeaks should do. Looks like a feature creep.

Expanded features increases complexity and testing. For example, these are exact features which probably should not even be in the GitLeaks in the first place. Why to bother HOW the git repository is delivered for scanning, supporting dozens of scenarios with increasingly complex testing? Let people define and implement that on their own pace, why not?
  
* Hit error when trying to scan github enterprise using user #245
* Can't scan an org #220
* Missing option to ignore certificate issues #265
* There is an error trying to connect to ssh in the --github-user option. #277

As for this PR, why not to transform current output outside of GitLeaks and send it to s3, Azure, Google, syslog or other systems? For example, GitLeaks can be run in docker container and then anther docker container can handle output: post-process, enhance with more data and send to other systems. Not that many lines in any programming language, isn't it? That way, GitLeaks does one things, and does it REALLY great avoiding feature creeps. Just keep it simple. 

Meanwhile, GitLeaks has a room for improvement in very core functionality. Not that this one if not important, but these are the gaps in actual scanning capabilities.

* Positive look ahead support or multiple regexps per rule? #258
* More tracing for findings and rules? #254
* Only scan additions, ignore removals #207
* Whitelisting per-rule? #255
* Ability to define positive/negatives datasets for rules? #256 
* Ability to define a folder with *.toml configirations #257
* and others

cc @zricethezav

**Comment by mtulio** [comment]
Hi @avishnyakov,

Thanks for your feedback.

I agree with you that is out of the scope of gitleaks to support different “backends”.

It was a result of an improvement that I identify, and I had to develop after writing too many lines in the shell script to:
- format json output lines
- too many string transformation to pipe the result to logger command
- taking too long time waiting for execution, sometime dozens hours waiting for an result, takes me necessity to streaming results to external syslog processor (ELK, Graylog, etc), and then process to create some metrics and alarms.

I understand that has a lot of improvements and issues, mainly when we need to run in thousands of repos a day (taking more than a day), but I just wanted to give back the local implementation for this project that is helping us to improve the security of our repos.

Thanks.,
Marco

**Comment by avishnyakov** [comment]
@mtulio agree on everything said.

I also work at a scale of ~1000 repositories processed daily. They come from different systems, and then GitLeaks output is enhanced, post-processed and pushed to analytics systems. GitLeaks outputs its raw data, and then custom scripts take over enhancing data, post-processing and pushing to data storage and analytics systems.

Definitely, there is an opportunity to contribute. The question is how to get it right. I am very much interested in your work around Elasticsearch and Syslog server. From my end, I can help with Azure storage and Azure Application Insights. 

Maybe we can figure out a small contrib project around GitLeaks output? I also have several more ideas which aren't in issues yet, keen to get your feedback.

**Comment by mtulio** [comment]
Hi @avishnyakov,

It sounds good. I am currently using Graylog (that is also using ES as storage) as log processor from syslog raw data. I started the project last week and, as we’ve talked, we can explore too much more from this raw data. Now I am carrying about to accurate and dedup of issues found on every output.

It will be a pleasure to discuss/contrib to this project.

**Pull request closed without merging**
