### PR TITLE
Fix reading from symlinks

### PR DESCRIPTION
**Pull request by zaycev**
### Description:
Fixes bug in handling symlinks introduced in #621.

### Checklist:

* [X] Does your PR pass tests?
* [ ] Have you written new tests for your changes?
* [X] Have you lint your code locally prior to submission?

### CODE REVIEW

**Comment by zricethezav** [comment]
@zaycev what is the current bug behavior? Could you provide a little more context on what this PR fixes?

**Comment by zaycev** [comment]
> @zaycev what is the current bug behavior? Could you provide a little more context on what this PR fixes?

For sure, the version on the master will initialize buffer with a path to the target instead of content of it:
```
if fc, err := os.Readlink(fn); err == nil {
  workTreeBuf = bytes.NewBufferString(fc) // <- fc contains path
} else if _, err := io.Copy(workTreeBuf, workTreeFile); err != nil {
  return scannerReport, err
}
```

**Comment by EliSchleifer** [comment]
@zricethezav - Hey zachary, any chance we can get this fix merged?

**Comment by zricethezav** [comment]
Closing this PR as it compares against an outdated version of Gitleaks

**Pull request closed without merging**
