### PR TITLE
adding jwt tokens with padding format "="

### PR DESCRIPTION
**Pull request by icecream-monster**
### Description:
Explain the purpose of the PR.

### Checklist:

* [x] Does your PR pass tests?
* [x] Have you written new tests for your changes?
* [x] Have you lint your code locally prior to submission?

### CODE REVIEW

**Comment by zricethezav** [comment]
@icecream-monster I agree with these changes. Would you mind updating the config using the directions described here https://github.com/zricethezav/gitleaks/blob/master/CONTRIBUTING.md?

**Comment by icecream-monster** [comment]
✅ done, ensured the auto-removed `Database.refactorlog` part was put back into `gitleaks.toml`

**Comment by icecream-monster** [comment]
soft ping on this PR @zricethezav?

**Comment by zricethezav** [comment]
thanks @icecream-monster lgtm!

**Pull request merged**
