### PR TITLE
Org python script

### PR DESCRIPTION
**Pull request by lucas-apd**
### Description:
Python Script to scan all org repos

### Checklist:

* [x] Does your PR pass tests?
* [x] Have you written new tests for your changes?
* [x] Have you lint your code locally prior to submission?

### CODE REVIEW

**Comment by w0rmr1d3r** [comment]
Hey @lucas-apd !
I found that a single for loop might not be very efficient for organizations with more than 100 repos (for example).
So I created this repo -> https://github.com/w0rmr1d3r/cloner
in order to clone efficiently all the repos in an organization. I'm still building it, but I believe you can already test it if you want to do so. That way we would only need to use my repo first and then pass your script to only run gitleaks.

What do you think? Do you like the idea?

Cheers!

**Comment by lucas-apd** [comment]
> Hey @lucas-apd ! I found that a single for loop might not be very efficient for organizations with more than 100 repos (for example). So I created this repo -> https://github.com/w0rmr1d3r/cloner in order to clone efficiently all the repos in an organization. I'm still building it, but I believe you can already test it if you want to do so. That way we would only need to use my repo first and then pass your script to only run gitleaks.
> 
> What do you think? Do you like the idea?
> 
> Cheers!
> 
> PS (and a hint): In version v8.0.0 of gitleaks, the cloning is deprecated...

Nice, @w0rmr1d3r . lets do this!

**Comment by zricethezav** [comment]
Hi @lucas-apd, would you mind resolving merge conflicts, testing on the latest release of gitleaks, and renaming the file to `scripts/org-scan.py`?

**Comment by zricethezav** [comment]
@foolioo good point, this would actually be better suited for a `scripts` or `tools` repo in  our org: https://github.com/gitleaks.

Gonna close this PR and follow-up in an issue

**Pull request closed without merging**
